name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          docker pull node:22-alpine
          docker run node:22-alpine node -v
          docker run node:22-alpine npm -v

      - name: Install dependencies
        run: docker run -v ${{ github.workspace }}:/app -w /app node:22-alpine sh -c "apk add --no-cache git && npm install"

      - name: Build Angular app
        run: docker run -v ${{ github.workspace }}:/app -w /app node:22-alpine sh -c "npm run build -- --prod --base-href='/megha-kaul/'"

      - name: Deploy to GitHub Pages
        run: docker run -v ${{ github.workspace }}:/app -w /app node:22-alpine sh -c "npx angular-cli-ghpages --dir=dist/website-v2"
